using System.Collections.Generic;
using System.Net;
using Shooter.Source.Dumies.Enemies;
using Shooter.Source.Enums;
using Shooter.Source.Models.Levels;

namespace Shooter.Source.Factories.Enemies
{
    public class EnemiesLevelSeven
    {
        public static List<EnemySection> GetEnemies()
        {
            return new List<EnemySection>()
            {
                new EnemySection(10, false, new DCommon(100, 9), new DCommon(1400, 9)),
                new EnemySection(10, false, new DCommon(200, 9), new DCommon(1300, 9)),
                new EnemySection(10, false, new DCommon(300, 9), new DCommon(1200, 9)),
                new EnemySection(10, false, new DCommon(400, 9), new DCommon(1100, 9)),
                new EnemySection(10, false, new DCommon(500, 9), new DCommon(1000, 9)),
                new EnemySection(10, false, new DCommon(600, 9), new DCommon(900, 9)),
                new EnemySection(10, false, new DCommon(700, 9), new DCommon(800, 9)),
                new EnemySection(10, false, new DCommon(600, 9), new DCommon(900, 9)),
                new EnemySection(10, false, new DCommon(500, 9), new DCommon(1000, 9)),
                new EnemySection(10, false, new DCommon(400, 9), new DCommon(1100, 9)),
                new EnemySection(10, false, new DCommon(300, 9), new DCommon(1200, 9)),
                new EnemySection(10, false, new DCommon(200, 9), new DCommon(1300, 9)),
                new EnemySection(10, false, new DCommon(100, 9), new DCommon(1400, 9)),
                new EnemySection(150, false, new DCrusader(100, 1)
                                          , new DCrusader(300, 1.8f)
                                          , new DCrusader(500, 2.6f)
                                          , new DCrusader(700, 3.4f)
                                          , new DCrusader(900, 4.2f) 
                                          , new DCrusader(1100, 5f)
                                          , new DCrusader(1300, 5.8f)),
                new EnemySection(30, false, new DBomber(100), new DDasher(1400)),                                    
                new EnemySection(10, false, new DLazer(500), new DFollower(700, EEnemyProjectileType.Light)),
                new EnemySection(500, false, new DSpread(100, EEnemyProjectileType.Light), new DSpread(1400, EEnemyProjectileType.Light), new DSpread(750, EEnemyProjectileType.Normal)),                        
                new EnemySection(10, false, new DDasher(1100)),                              
                new EnemySection(10, false, new DDasher(1100)),                              
                new EnemySection(10, false, new DDasher(1100)),                              
                new EnemySection(10, false, new DDasher(1100)),                              
                new EnemySection(10, false, new DDasher(1100)),                              
                new EnemySection(10, false, new DDasher(1100)),                              
                new EnemySection(10, false, new DDasher(1100)),                              
                new EnemySection(10, false, new DDasher(1100)),                              
                new EnemySection(160, false, new DDasher(1100)), 


                new EnemySection(40, false, new DGooder(200, true), new DSniper(300, EEnemyProjectileType.Light)),                     
                new EnemySection(40, false, new DGooder(200, true), new DSniper(100, EEnemyProjectileType.Light)),                     
                new EnemySection(40, false, new DGooder(200, true), new DSniper(500, EEnemyProjectileType.Light)),                     
                new EnemySection(40, false, new DGooder(200, true), new DSniper(600, EEnemyProjectileType.Light)),                     
                new EnemySection(40, false, new DGooder(200, true), new DSniper(400, EEnemyProjectileType.Light)),                     
                new EnemySection(40, false, new DGooder(200, true), new DSniper(700, EEnemyProjectileType.Light)),     

                new EnemySection(10, false, new DFollower(100, EEnemyProjectileType.Normal)),                     
                new EnemySection(10, false, new DFollower(200, EEnemyProjectileType.Normal)),                     
                new EnemySection(10, false, new DFollower(300, EEnemyProjectileType.Normal)),                     
                new EnemySection(10, false, new DFollower(400, EEnemyProjectileType.Normal)),                     
                new EnemySection(10, false, new DFollower(500, EEnemyProjectileType.Normal)),

                new EnemySection(50, false, new DSniper(100, EEnemyProjectileType.Normal), 
                                            new DSniper(300, EEnemyProjectileType.Normal), 
                                            new DSniper(500, EEnemyProjectileType.Normal), 
                                            new DSniper(700, EEnemyProjectileType.Homing),
                                            new DSniper(900, EEnemyProjectileType.Normal),
                                            new DSniper(1100, EEnemyProjectileType.Normal),
                                            new DSniper(1300, EEnemyProjectileType.Normal)),
                                            
                new EnemySection(50, false, new DSniper(100, EEnemyProjectileType.Normal), 
                                            new DSniper(300, EEnemyProjectileType.Normal), 
                                            new DSniper(500, EEnemyProjectileType.Normal), 
                                            new DSniper(700, EEnemyProjectileType.Homing),
                                            new DSniper(900, EEnemyProjectileType.Normal),
                                            new DSniper(1100, EEnemyProjectileType.Normal),
                                            new DSniper(1300, EEnemyProjectileType.Normal)),
                
                new EnemySection(600, false, new DSniper(100, EEnemyProjectileType.Normal), 
                                            new DSniper(300, EEnemyProjectileType.Normal), 
                                            new DSniper(500, EEnemyProjectileType.Normal), 
                                            new DSniper(700, EEnemyProjectileType.Homing),
                                            new DSniper(900, EEnemyProjectileType.Normal),
                                            new DSniper(1100, EEnemyProjectileType.Normal),
                                            new DSniper(1300, EEnemyProjectileType.Normal)),

                new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Normal), new DShoter(1300, EEnemyProjectileType.Normal)),
                new EnemySection(10, false, new DStomper(200)),
                new EnemySection(10, false, new DStomper(400)),
                new EnemySection(10, false, new DShoter(300, EEnemyProjectileType.Normal), new DShoter(1100, EEnemyProjectileType.Normal)),
                new EnemySection(10, false, new DStomper(800)),
                new EnemySection(500, false, new DStomper(1000)),

                new EnemySection(10, false, new DDasher(100)),
                new EnemySection(10, false, new DDasher(200)),
                new EnemySection(10, false, new DDasher(300)),
                new EnemySection(10, false, new DDasher(400)),
                new EnemySection(10, false, new DDasher(500)),
                new EnemySection(10, false, new DDasher(600)),
                new EnemySection(10, false, new DDasher(700)),
                new EnemySection(10, false, new DDasher(800)),
                new EnemySection(10, false, new DDasher(900)),
                new EnemySection(10, false, new DDasher(1000)),
                new EnemySection(10, false, new DDasher(1100)),
                new EnemySection(10, false, new DDasher(1200)),
                new EnemySection(200, false, new DDasher(1300)),

                new EnemySection(10, false, new DGooder(100, false), new DOrbiter()),
                new EnemySection(10, false, new DGooder(200, false)),
                new EnemySection(10, false, new DGooder(300, false), new DOrbiter()),
                new EnemySection(10, false, new DGooder(400, false)),
                new EnemySection(10, false, new DGooder(500, false), new DOrbiter()),
                new EnemySection(10, false, new DGooder(600, false)),
                new EnemySection(10, false, new DGooder(700, false), new DOrbiter()),
                new EnemySection(10, false, new DGooder(800, false)),
                new EnemySection(10, false, new DGooder(900, false), new DOrbiter()),
                new EnemySection(10, false, new DGooder(1000, false)),
                new EnemySection(10, false, new DGooder(1100, false), new DOrbiter()),
                new EnemySection(10, false, new DGooder(1200, false)),
                new EnemySection(200, false, new DGooder(1300, false), new DOrbiter()),

                new EnemySection(200, false, new DFollower(100, EEnemyProjectileType.Strong), new DFollower(500, EEnemyProjectileType.Strong), new DFollower(1300, EEnemyProjectileType.Strong)),
                new EnemySection(600, false, new DFollower(100, EEnemyProjectileType.Strong), new DFollower(500, EEnemyProjectileType.Strong), new DFollower(1300, EEnemyProjectileType.Strong)),

                new EnemySection(20, false, new DCommon(100, 3),
                                             new DCommon(150, 3),
                                             new DCommon(200, 3),
                                             new DCommon(250, 3),
                                             new DCommon(300, 3),
                                             new DCommon(350, 3),
                                             new DCommon(400, 3),
                                             new DCommon(450, 3),
                                             new DCommon(500, 3),
                                             new DCommon(550, 3),
                                             new DCommon(600, 3),
                                             new DCommon(650, 3),
                                             new DCommon(700, 3),
                                             new DCommon(750, 3),
                                             new DCommon(800, 3),
                                             new DCommon(850, 3),
                                             new DCommon(900, 3),
                                             new DCommon(950, 3),
                                             new DCommon(1000, 3),
                                             new DCommon(1050, 3),
                                             new DCommon(1100, 3),
                                             new DCommon(1150, 3),
                                             new DCommon(1200, 3),
                                             new DCommon(1250, 3),
                                             new DCommon(1300, 3),
                                             new DCommon(1350, 3),
                                             new DCommon(1400, 3),
                                             new DLighting(500)),
                
                new EnemySection(20, false, new DCommon(100, 3),
                                             new DCommon(150, 3),
                                             new DCommon(200, 3),
                                             new DCommon(250, 3),
                                             new DCommon(300, 3),
                                             new DCommon(350, 3),
                                             new DCommon(400, 3),
                                             new DCommon(450, 3),
                                             new DCommon(500, 3),
                                             new DCommon(550, 3),
                                             new DCommon(600, 3),
                                             new DCommon(650, 3),
                                             new DCommon(700, 3),
                                             new DCommon(750, 3),
                                             new DCommon(800, 3),
                                             new DCommon(850, 3),
                                             new DCommon(900, 3),
                                             new DCommon(950, 3),
                                             new DCommon(1000, 3),
                                             new DCommon(1050, 3),
                                             new DCommon(1100, 3),
                                             new DCommon(1150, 3),
                                             new DCommon(1200, 3),
                                             new DCommon(1250, 3),
                                             new DCommon(1300, 3),
                                             new DCommon(1350, 3),
                                             new DCommon(1400, 3),
                                             new DShoter(500, EEnemyProjectileType.Light)),

            new EnemySection(200, false, new DCommon(100, 3),
                                             new DCommon(150, 3),
                                             new DCommon(200, 3),
                                             new DCommon(250, 3),
                                             new DCommon(300, 3),
                                             new DCommon(350, 3),
                                             new DCommon(400, 3),
                                             new DCommon(450, 3),
                                             new DCommon(500, 3),
                                             new DCommon(550, 3),
                                             new DCommon(600, 3),
                                             new DCommon(650, 3),
                                             new DCommon(700, 3),
                                             new DCommon(750, 3),
                                             new DCommon(800, 3),
                                             new DCommon(850, 3),
                                             new DCommon(900, 3),
                                             new DCommon(950, 3),
                                             new DCommon(1000, 3),
                                             new DCommon(1050, 3),
                                             new DCommon(1100, 3),
                                             new DCommon(1150, 3),
                                             new DCommon(1200, 3),
                                             new DCommon(1250, 3),
                                             new DCommon(1300, 3),
                                             new DCommon(1350, 3),
                                             new DCommon(1400, 3)),

            new EnemySection(20, false, new DLighting(50)),
            new EnemySection(20, false, new DLighting(100)),
            new EnemySection(20, false, new DLighting(150)),
            new EnemySection(20, false, new DLighting(200)),
            new EnemySection(20, false, new DLighting(250)),
            new EnemySection(20, false, new DLighting(300)),
            new EnemySection(20, false, new DLighting(350)),
            new EnemySection(20, false, new DLighting(400)),
            new EnemySection(20, false, new DLighting(450)),
            new EnemySection(20, false, new DLighting(500)),
            new EnemySection(20, false, new DLighting(550)),
            new EnemySection(20, false, new DLighting(600)),
            new EnemySection(20, false, new DLighting(650)),
            new EnemySection(20, false, new DLighting(700)),
            new EnemySection(20, false, new DLighting(750)),
            new EnemySection(20, false, new DLighting(800)),
            new EnemySection(20, false, new DLighting(850)),
            new EnemySection(20, false, new DLighting(900)),
            new EnemySection(20, false, new DLighting(950)),
            new EnemySection(20, false, new DLighting(1000)),
            new EnemySection(20, false, new DLighting(1050)),
            new EnemySection(20, false, new DLighting(1100)),
            new EnemySection(20, false, new DLighting(1150)),
            new EnemySection(20, false, new DLighting(1200)),
            new EnemySection(20, false, new DLighting(1250)),
            new EnemySection(20, false, new DLighting(1300)),
            new EnemySection(20, false, new DLighting(1350)),
            new EnemySection(100, false, new DLighting(1400)),

            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(200, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(300, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(400, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(500, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(600, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(700, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(800, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(900, EEnemyProjectileType.Light)),

            new EnemySection(10, false, new DDasher(100)),
            new EnemySection(10, false, new DDasher(200)),
            new EnemySection(10, false, new DDasher(300)),
            new EnemySection(10, false, new DDasher(400)),
            new EnemySection(10, false, new DDasher(500)),
            new EnemySection(10, false, new DDasher(600)),
            new EnemySection(10, false, new DDasher(700)),
            new EnemySection(10, false, new DDasher(800)),
            new EnemySection(10, false, new DDasher(900)),

            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(200, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(300, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(400, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(500, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(600, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(700, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(800, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(900, EEnemyProjectileType.Light)),

            new EnemySection(10, false, new DDasher(100)),
            new EnemySection(10, false, new DDasher(200)),
            new EnemySection(10, false, new DDasher(300)),
            new EnemySection(10, false, new DDasher(400)),
            new EnemySection(10, false, new DDasher(500)),
            new EnemySection(10, false, new DDasher(600)),
            new EnemySection(10, false, new DDasher(700)),
            new EnemySection(10, false, new DDasher(800)),
            new EnemySection(10, false, new DDasher(900)),

            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(200, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(300, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(400, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(500, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(600, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(700, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(800, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(900, EEnemyProjectileType.Light)),

            new EnemySection(10, false, new DDasher(100)),
            new EnemySection(10, false, new DDasher(200)),
            new EnemySection(10, false, new DDasher(300)),
            new EnemySection(10, false, new DDasher(400)),
            new EnemySection(10, false, new DDasher(500)),
            new EnemySection(10, false, new DDasher(600)),
            new EnemySection(10, false, new DDasher(700)),
            new EnemySection(10, false, new DDasher(800)),
            new EnemySection(10, false, new DDasher(900)),

            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(200, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(300, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(400, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(500, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(600, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(700, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(800, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DShoter(900, EEnemyProjectileType.Light)),

            new EnemySection(10, false, new DDasher(100)),
            new EnemySection(10, false, new DDasher(200)),
            new EnemySection(10, false, new DDasher(300)),
            new EnemySection(10, false, new DDasher(400)),
            new EnemySection(10, false, new DDasher(500)),
            new EnemySection(10, false, new DDasher(600)),
            new EnemySection(10, false, new DDasher(700)),
            new EnemySection(10, false, new DDasher(800)),
            new EnemySection(10, false, new DDasher(900)),

            new EnemySection(10, false, new DLighting(50)),
            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(100)),
            new EnemySection(10, false, new DShoter(200, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(150)),
            new EnemySection(10, false, new DShoter(300, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(200)),
            new EnemySection(10, false, new DShoter(400, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(250)),
            new EnemySection(10, false, new DShoter(500, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(300)),
            new EnemySection(10, false, new DShoter(600, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(350)),
            new EnemySection(10, false, new DShoter(700, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(400)),
            new EnemySection(10, false, new DShoter(800, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(450)),
            new EnemySection(10, false, new DShoter(900, EEnemyProjectileType.Light)),

            new EnemySection(10, false, new DStomper(200)),
            new EnemySection(10, false, new DStomper(400)),

            new EnemySection(10, false, new DDasher(100)),
            new EnemySection(10, false, new DLighting(500)),
            new EnemySection(10, false, new DDasher(200)),
            new EnemySection(10, false, new DLighting(550)),
            new EnemySection(10, false, new DDasher(300)),
            new EnemySection(20, false, new DLighting(600)),
            new EnemySection(10, false, new DDasher(400)),
            new EnemySection(20, false, new DLighting(650)),
            new EnemySection(10, false, new DDasher(500)),

            new EnemySection(10, false, new DStomper(200)),
            new EnemySection(10, false, new DStomper(400)),

            new EnemySection(20, false, new DLighting(700)),
            new EnemySection(10, false, new DDasher(600)),
            new EnemySection(10, false, new DLighting(750)),
            new EnemySection(10, false, new DDasher(700)),
            new EnemySection(10, false, new DLighting(800)),
            new EnemySection(10, false, new DDasher(800)),
            new EnemySection(10, false, new DLighting(850)),

            new EnemySection(10, false, new DStomper(200)),
            new EnemySection(10, false, new DStomper(400)),

            new EnemySection(10, false, new DDasher(900)),
            new EnemySection(10, false, new DLighting(900)),

            new EnemySection(10, false, new DLighting(50)),
            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(100)),
            new EnemySection(10, false, new DShoter(200, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(150)),

            new EnemySection(10, false, new DStomper(200)),
            new EnemySection(10, false, new DStomper(400)),

            new EnemySection(10, false, new DShoter(300, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(200)),
            new EnemySection(10, false, new DShoter(400, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(250)),
            new EnemySection(10, false, new DShoter(500, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(300)),
            new EnemySection(10, false, new DShoter(600, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(350)),
            new EnemySection(10, false, new DShoter(700, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(400)),
            new EnemySection(10, false, new DShoter(800, EEnemyProjectileType.Light)),
            new EnemySection(10, false, new DLighting(450)),
            new EnemySection(10, false, new DShoter(900, EEnemyProjectileType.Light)),

            new EnemySection(10, false, new DDasher(100)),
            new EnemySection(10, false, new DLighting(500)),
            new EnemySection(10, false, new DDasher(200)),
            new EnemySection(10, false, new DLighting(550)),
            new EnemySection(10, false, new DDasher(300)),
            new EnemySection(10, false, new DLighting(600)),
            new EnemySection(10, false, new DDasher(400)),
            new EnemySection(10, false, new DLighting(650)),
            new EnemySection(10, false, new DDasher(500)),
            new EnemySection(10, false, new DLighting(700)),
            new EnemySection(10, false, new DDasher(600)),
            new EnemySection(10, false, new DLighting(750)),
            new EnemySection(10, false, new DDasher(700)),
            new EnemySection(10, false, new DLighting(800)),
            new EnemySection(10, false, new DDasher(800)),
            new EnemySection(10, false, new DLighting(850)),
            new EnemySection(10, false, new DDasher(900)),
            new EnemySection(10, false, new DLighting(900)),

            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Strong),
                                        new DShoter(200, EEnemyProjectileType.Strong),
                                        new DShoter(300, EEnemyProjectileType.Strong),
                                        new DShoter(400, EEnemyProjectileType.Strong),
                                        new DShoter(500, EEnemyProjectileType.Strong),
                                        new DShoter(600, EEnemyProjectileType.Strong),
                                        new DShoter(700, EEnemyProjectileType.Strong),
                                        new DShoter(800, EEnemyProjectileType.Strong),
                                        new DShoter(900, EEnemyProjectileType.Strong),
                                        new DShoter(1000, EEnemyProjectileType.Strong),
                                        new DShoter(1100, EEnemyProjectileType.Strong),
                                        new DShoter(1200, EEnemyProjectileType.Strong),
                                        new DShoter(1300, EEnemyProjectileType.Strong),
                                        new DShoter(1400, EEnemyProjectileType.Strong)),
            
            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Strong),
                                        new DShoter(200, EEnemyProjectileType.Strong),
                                        new DShoter(300, EEnemyProjectileType.Strong),
                                        new DShoter(400, EEnemyProjectileType.Strong),
                                        new DShoter(500, EEnemyProjectileType.Strong),
                                        new DShoter(600, EEnemyProjectileType.Strong),
                                        new DShoter(700, EEnemyProjectileType.Strong),
                                        new DShoter(800, EEnemyProjectileType.Strong),
                                        new DShoter(900, EEnemyProjectileType.Strong),
                                        new DShoter(1000, EEnemyProjectileType.Strong),
                                        new DShoter(1100, EEnemyProjectileType.Strong),
                                        new DShoter(1200, EEnemyProjectileType.Strong),
                                        new DShoter(1300, EEnemyProjectileType.Strong),
                                        new DShoter(1400, EEnemyProjectileType.Strong)),

            new EnemySection(10, false, new DShoter(100, EEnemyProjectileType.Strong),
                                        new DShoter(200, EEnemyProjectileType.Strong),
                                        new DShoter(300, EEnemyProjectileType.Strong),
                                        new DShoter(400, EEnemyProjectileType.Strong),
                                        new DShoter(500, EEnemyProjectileType.Strong),
                                        new DShoter(600, EEnemyProjectileType.Strong),
                                        new DShoter(700, EEnemyProjectileType.Strong),
                                        new DShoter(800, EEnemyProjectileType.Strong),
                                        new DShoter(900, EEnemyProjectileType.Strong),
                                        new DShoter(1000, EEnemyProjectileType.Strong),
                                        new DShoter(1100, EEnemyProjectileType.Strong),
                                        new DShoter(1200, EEnemyProjectileType.Strong),
                                        new DShoter(1300, EEnemyProjectileType.Strong),
                                        new DShoter(1400, EEnemyProjectileType.Strong)),
            
            new EnemySection(100, false, new DShoter(100, EEnemyProjectileType.Strong),
                                        new DShoter(200, EEnemyProjectileType.Strong),
                                        new DShoter(300, EEnemyProjectileType.Strong),
                                        new DShoter(400, EEnemyProjectileType.Strong),
                                        new DShoter(500, EEnemyProjectileType.Strong),
                                        new DShoter(600, EEnemyProjectileType.Strong),
                                        new DShoter(700, EEnemyProjectileType.Strong),
                                        new DShoter(800, EEnemyProjectileType.Strong),
                                        new DShoter(900, EEnemyProjectileType.Strong),
                                        new DShoter(1000, EEnemyProjectileType.Strong),
                                        new DShoter(1100, EEnemyProjectileType.Strong),
                                        new DShoter(1200, EEnemyProjectileType.Strong),
                                        new DShoter(1300, EEnemyProjectileType.Strong),
                                        new DShoter(1400, EEnemyProjectileType.Strong)),

            };

        }        
    }
}