using System.Collections.Generic;
using Shooter.Source.Dumies.Enemies;
using Shooter.Source.Enums;
using Shooter.Source.Models.Levels;

namespace Shooter.Source.Factories.Enemies
{
    public static class EnemiesLevelTwo
    {
        public static List<EnemySection> GetEnemies()
        {

            return new List<EnemySection>()
            {
                new(50, true, new DStomper(100)),

                new(20, false, new DSniper(400, EEnemyProjectileType.Homing)),

                new(20, false, new DCommon(300, 10), new DCommon(100, 10)),
                new(20, false, new DCommon(500, 10), new DCommon(1000, 10)),
                new(20, false, new DCommon(900, 10), new DCommon(1300, 10)),
                new(20, false, new DCommon(1100, 10), new DCommon(100, 10)),
                new(20, false, new DCommon(200, 10), new DCommon(800, 10)),
                new(20, false, new DCommon(700, 10)),
                new(20, false, new DCommon(800, 10)),

                new(30, false, new DSpread(300, EEnemyProjectileType.Normal, 5), new DSpread(1100, EEnemyProjectileType.Normal, 5)),
                new(30, false, new DSpread(400, EEnemyProjectileType.Normal, 5), new DSpread(1000, EEnemyProjectileType.Normal, 5)),
                new(30, false, new DSpread(500, EEnemyProjectileType.Normal, 5), new DSpread(900, EEnemyProjectileType.Normal, 5)),
                new(30, false, new DSpread(600, EEnemyProjectileType.Normal, 5), new DSpread(800, EEnemyProjectileType.Normal, 5)),
                new(30, true, new DSpread(700, EEnemyProjectileType.Normal, 5), new DStomper(750), new DStomper(650)),

                new(20, false, new DSniper(400, EEnemyProjectileType.Homing)),

                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),

                new(20, false, new DSniper(600, EEnemyProjectileType.Homing)),
                new(30, false, new DSpread(50, EEnemyProjectileType.Normal, 5), new DSpread(1350, EEnemyProjectileType.Normal, 5)),

                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, false, new DStomper(1300)),
                new(10, false, new DStomper(100)),
                new(10, true, new DStomper(1300)),

                new(20, false, new DSniper(100, EEnemyProjectileType.Homing), new DStomper(1300)),
                new(30, false, new DCommon(700, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DSpread(700, EEnemyProjectileType.Normal, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DSpread(700, EEnemyProjectileType.Normal, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DSpread(700, EEnemyProjectileType.Normal, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DSpread(700, EEnemyProjectileType.Normal, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DSpread(700, EEnemyProjectileType.Normal, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DSpread(700, EEnemyProjectileType.Normal, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DSpread(700, EEnemyProjectileType.Normal, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DSpread(700, EEnemyProjectileType.Normal, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(30, false, new DCommon(700, 7), new DCommon(600, 7), new DCommon(800, 7)),
                new(20, true, new DStomper(1300)),

                new(10, false, new DSniper(100, EEnemyProjectileType.Homing)),
                new(20, false, new DCommon(188, 5), new DCommon(841, 9), new DCommon(117, 9), new DCommon(1010, 10), new DCommon(206, 8)),
                new(20, false, new DCommon(420, 10), new DCommon(514, 7), new DCommon(931, 8), new DCommon(1110, 9), new DCommon(260, 5)),
                new(20, false, new DCommon(558, 10), new DCommon(1243, 7), new DCommon(835, 9), new DCommon(758, 5), new DCommon(1035, 6)),
                new(20, false, new DCommon(1337, 7), new DCommon(1062, 9), new DCommon(952, 8), new DCommon(388, 5), new DCommon(890, 6)),
                new(20, false, new DCommon(86, 9), new DCommon(1279, 10), new DCommon(580, 9), new DCommon(187, 8), new DCommon(560, 7)),
                new(20, false, new DCommon(1064, 6), new DCommon(90, 8), new DCommon(625, 10), new DCommon(185, 5), new DCommon(278, 6)),
                new(20, false, new DCommon(1143, 9), new DCommon(1323, 7), new DCommon(281, 5), new DCommon(565, 10), new DCommon(137, 8)),
                new(20, false, new DCommon(341, 10), new DCommon(1156, 5), new DCommon(811, 7), new DCommon(1214, 9), new DCommon(313, 6)),
                new(20, false, new DCommon(752, 8), new DCommon(354, 6), new DCommon(1033, 9), new DCommon(430, 7), new DCommon(1067, 5)),
                new(20, false, new DCommon(322, 6), new DCommon(747, 9), new DCommon(1127, 6), new DCommon(1182, 8), new DCommon(701, 10)),
                new(20, false, new DCommon(893, 9), new DCommon(744, 7), new DCommon(621, 5), new DCommon(1347, 10), new DCommon(714, 9)),
                new(20, false, new DCommon(368, 7), new DCommon(1166, 8), new DCommon(902, 10), new DCommon(1308, 5), new DCommon(944, 7)),
                new(20, false, new DCommon(69, 5), new DCommon(943, 6), new DCommon(1204, 9), new DCommon(458, 7), new DCommon(351, 5)),
                new(20, false, new DCommon(214, 10), new DCommon(969, 9), new DCommon(886, 6), new DCommon(916, 8), new DCommon(606, 10)),
                new(20, false, new DCommon(579, 8), new DCommon(84, 7), new DCommon(906, 5), new DCommon(345, 10), new DCommon(795, 8)),
                new(20, false, new DCommon(182, 6), new DCommon(1175, 5), new DCommon(673, 7), new DCommon(888, 9), new DCommon(955, 6)),
                new(20, false, new DCommon(1266, 9), new DCommon(481, 10), new DCommon(1017, 8), new DCommon(206, 6), new DCommon(811, 9)),
                new(20, false, new DCommon(130, 7), new DCommon(1107, 8), new DCommon(423, 10), new DCommon(355, 5), new DCommon(858, 7)),
                new(20, false, new DCommon(529, 5), new DCommon(80, 6), new DCommon(421, 9), new DCommon(1303, 7), new DCommon(539, 5)),
                new(20, false, new DCommon(752, 10), new DCommon(697, 9), new DCommon(1114, 6), new DCommon(630, 8), new DCommon(462, 10)),
                new(20, false, new DCommon(515, 8), new DCommon(607, 7), new DCommon(1313, 5), new DCommon(793, 10), new DCommon(696, 8)),
                new(20, false, new DCommon(303, 6), new DCommon(111, 5), new DCommon(1306, 7), new DCommon(1070, 9), new DCommon(294, 6)),
                new(20, false, new DCommon(1060, 9), new DCommon(575, 10), new DCommon(231, 8), new DCommon(785, 6), new DCommon(1256, 9)),
                new(20, false, new DCommon(1116, 7), new DCommon(632, 8), new DCommon(752, 10), new DCommon(1090, 5), new DCommon(954, 7)),
                new(20, false, new DCommon(309, 5), new DCommon(630, 6), new DCommon(1289, 9), new DCommon(270, 7), new DCommon(883, 5)),
                new(20, false, new DCommon(702, 10), new DCommon(153, 9), new DCommon(988, 6), new DCommon(292, 8), new DCommon(998, 10)),
                new(20, false, new DCommon(540, 8), new DCommon(952, 7), new DCommon(1098, 5), new DCommon(202, 10), new DCommon(1214, 8)),
                new(20, true, new DCommon(659, 6), new DCommon(1315, 5), new DCommon(627, 7), new DCommon(231, 9), new DCommon(524, 6)),

                new(10, false, new DSniper(100, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(200, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(300, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(400, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(500, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(600, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(700, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(800, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(900, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(1000, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(1100, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(1200, EEnemyProjectileType.Homing)),
                new(10, false, new DSniper(1300, EEnemyProjectileType.Homing)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(10, false, new DFollower(1300, EEnemyProjectileType.Normal)),
                new(10, false, new DFollower(100, EEnemyProjectileType.Normal)),

                new(2, false, new DCurver(50)),
                new(2, false, new DCurver(100)),
                new(2, false, new DCurver(150)),
                new(2, false, new DCurver(200)),
                new(2, false, new DCurver(250)),
                new(2, false, new DCurver(300)),
                new(2, false, new DCurver(350)),
                new(2, false, new DCurver(400)),
                new(2, false, new DCurver(450)),
                new(2, false, new DCurver(500)),
                new(2, false, new DCurver(550)),
                new(2, false, new DCurver(600)),
                new(2, false, new DCurver(650)),
                new(2, false, new DCurver(700)),
                new(2, false, new DCurver(750)),
                new(2, false, new DCurver(800)),
                new(2, false, new DCurver(850)),
                new(2, false, new DCurver(900)),
                new(2, false, new DCurver(950)),
                new(2, false, new DCurver(1000)),
                new(2, false, new DCurver(1050)),
                new(2, false, new DCurver(1100)),
                new(2, false, new DCurver(1150)),
                new(2, false, new DCurver(1200)),
                new(2, false, new DCurver(1250)),
                new(2, false, new DCurver(1300)),
                new(2, true, new DCurver(1350)),

                new(5, false, new DSniper(100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(300, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(400, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(500, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(600, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(700, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(800, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(900, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1000, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1300, EEnemyProjectileType.Normal)),

                new(5, false, new DSniper(100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(300, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(400, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(500, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(600, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(700, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(800, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(900, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1000, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1300, EEnemyProjectileType.Normal)),

                new(5, false, new DSniper(100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(300, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(400, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(500, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(600, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(700, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(800, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(900, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1000, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1300, EEnemyProjectileType.Normal)),

                new(5, false, new DSniper(100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(300, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(400, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(500, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(600, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(700, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(800, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(900, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1000, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1300, EEnemyProjectileType.Normal)),

                new(5, false, new DSniper(100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(300, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(400, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(500, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(600, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(700, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(800, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(900, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1000, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1300, EEnemyProjectileType.Normal)),

                new(5, false, new DSniper(100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(300, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(400, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(500, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(600, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(700, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(800, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(900, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1000, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1300, EEnemyProjectileType.Normal)),

                new(5, false, new DSniper(100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(300, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(400, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(500, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(600, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(700, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(800, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(900, EEnemyProjectileType.Normal)),
                new(5, false, new DFollower(1000, EEnemyProjectileType.Homing)),
                new(5, false, new DSniper(1100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1300, EEnemyProjectileType.Normal)),

                new(5, false, new DSniper(100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(300, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(400, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(500, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(600, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(700, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(800, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(900, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1000, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1100, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1200, EEnemyProjectileType.Normal)),
                new(5, false, new DSniper(1300, EEnemyProjectileType.Normal)),
            };

        }
    }
}