using System.Collections.Generic;
using Shooter.Source.Dumies.Enemies;
using Shooter.Source.Enums;
using Shooter.Source.Models.Levels;

namespace Shooter.Source.Factories.Enemies
{
    public class EnemiesLevelThree
    {
        public static List<EnemySection> GetEnemies()
        {
            return new List<EnemySection>()
            {
                new EnemySection(50, true, new DShoter(100, EEnemyProjectileType.Light),
                                           new DShoter(700, EEnemyProjectileType.Normal),
                                           new DShoter(1300, EEnemyProjectileType.Light)),

                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DSniper(100, Enums.EEnemyProjectileType.Light)),

                new EnemySection(60, false, new DSpread(700, Enums.EEnemyProjectileType.Light, 8)),
                new EnemySection(60, false, new DSpread(600, Enums.EEnemyProjectileType.Light, 8), new DSpread(800, Enums.EEnemyProjectileType.Light, 8)),
                new EnemySection(60, false, new DSpread(500, Enums.EEnemyProjectileType.Light, 8), new DSpread(900, Enums.EEnemyProjectileType.Light, 8)),
                new EnemySection(60, false, new DSpread(400, Enums.EEnemyProjectileType.Light, 8), new DSpread(1000, Enums.EEnemyProjectileType.Light, 8)),
                new EnemySection(60, false, new DSpread(300, Enums.EEnemyProjectileType.Light, 8), new DSpread(1100, Enums.EEnemyProjectileType.Light, 8), new DSpread(700, Enums.EEnemyProjectileType.Normal, 8)),
                new EnemySection(60, false, new DSpread(200, Enums.EEnemyProjectileType.Light, 8), new DSpread(1200, Enums.EEnemyProjectileType.Light, 8), new DSpread(800, Enums.EEnemyProjectileType.Normal, 8), new DSpread(600, Enums.EEnemyProjectileType.Normal, 8)),
                new EnemySection(60, true, new DSpread(100, Enums.EEnemyProjectileType.Light, 8), new DSpread(1300, Enums.EEnemyProjectileType.Light, 8), new DSpread(900, Enums.EEnemyProjectileType.Normal, 8), new DSpread(500, Enums.EEnemyProjectileType.Normal, 8)),

                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5), new DShoter(100, EEnemyProjectileType.Light), new DShoter(1300, EEnemyProjectileType.Light)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, false, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),
                new EnemySection(20, true, new DCommon(100, 5), new DCommon(200, 5), new DCommon(1300, 5), new DCommon(1200, 5)),

                new EnemySection(70, false, new DSniper(50, EEnemyProjectileType.Light),
                                            new DSniper(100, EEnemyProjectileType.Light),
                                            new DSniper(150, EEnemyProjectileType.Light),
                                            new DSniper(200, EEnemyProjectileType.Light),
                                            new DSniper(250, EEnemyProjectileType.Light),
                                            new DSniper(300, EEnemyProjectileType.Light),
                                            new DSniper(350, EEnemyProjectileType.Light),
                                            new DSniper(400, EEnemyProjectileType.Light),
                                            new DSniper(450, EEnemyProjectileType.Light),
                                            new DSniper(500, EEnemyProjectileType.Light),
                                            new DSniper(550, EEnemyProjectileType.Light),
                                            new DSniper(600, EEnemyProjectileType.Light),
                                            new DSniper(650, EEnemyProjectileType.Light),
                                            new DSniper(700, EEnemyProjectileType.Light),
                                            new DSniper(750, EEnemyProjectileType.Light),
                                            new DSniper(800, EEnemyProjectileType.Light),
                                            new DSniper(850, EEnemyProjectileType.Light),
                                            new DSniper(900, EEnemyProjectileType.Light),
                                            new DSniper(950, EEnemyProjectileType.Light),
                                            new DSniper(1000, EEnemyProjectileType.Light),
                                            new DSniper(1050, EEnemyProjectileType.Light),
                                            new DSniper(1100, EEnemyProjectileType.Light),
                                            new DSniper(1150, EEnemyProjectileType.Light),
                                            new DSniper(1200, EEnemyProjectileType.Light),
                                            new DSniper(1250, EEnemyProjectileType.Light),
                                            new DSniper(1300, EEnemyProjectileType.Light),
                                            new DSniper(1350, EEnemyProjectileType.Light)),
                    
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),

                new EnemySection(10, false, new DSniper(50, EEnemyProjectileType.Light),
                                            new DSniper(100, EEnemyProjectileType.Light),
                                            new DSniper(150, EEnemyProjectileType.Light),
                                            new DSniper(200, EEnemyProjectileType.Light),
                                            new DSniper(250, EEnemyProjectileType.Light),
                                            new DSniper(300, EEnemyProjectileType.Light),
                                            new DSniper(350, EEnemyProjectileType.Light),
                                            new DSniper(400, EEnemyProjectileType.Light),
                                            new DSniper(450, EEnemyProjectileType.Light),
                                            new DSniper(500, EEnemyProjectileType.Light),
                                            new DSniper(550, EEnemyProjectileType.Light),
                                            new DSniper(600, EEnemyProjectileType.Light),
                                            new DSniper(650, EEnemyProjectileType.Light),
                                            new DSniper(700, EEnemyProjectileType.Light),
                                            new DSniper(750, EEnemyProjectileType.Light),
                                            new DSniper(800, EEnemyProjectileType.Light),
                                            new DSniper(850, EEnemyProjectileType.Light),
                                            new DSniper(900, EEnemyProjectileType.Light),
                                            new DSniper(950, EEnemyProjectileType.Light),
                                            new DSniper(1000, EEnemyProjectileType.Light),
                                            new DSniper(1050, EEnemyProjectileType.Light),
                                            new DSniper(1100, EEnemyProjectileType.Light),
                                            new DSniper(1150, EEnemyProjectileType.Light),
                                            new DSniper(1200, EEnemyProjectileType.Light),
                                            new DSniper(1250, EEnemyProjectileType.Light),
                                            new DSniper(1300, EEnemyProjectileType.Light),
                                            new DSniper(1350, EEnemyProjectileType.Light)),

                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, false, new DFollower(300, EEnemyProjectileType.Light)),
                new EnemySection(40, true, new DFollower(300, EEnemyProjectileType.Light)),

                new EnemySection(50, false, new DSniper(50, EEnemyProjectileType.Light),
                                            new DSniper(100, EEnemyProjectileType.Light),
                                            new DSniper(150, EEnemyProjectileType.Light),
                                            new DSniper(200, EEnemyProjectileType.Light),
                                            new DSniper(250, EEnemyProjectileType.Light),
                                            new DSniper(300, EEnemyProjectileType.Light),
                                            new DSniper(350, EEnemyProjectileType.Light),
                                            new DSniper(400, EEnemyProjectileType.Light),
                                            new DSniper(450, EEnemyProjectileType.Light),
                                            new DSniper(500, EEnemyProjectileType.Light),
                                            new DSniper(550, EEnemyProjectileType.Light),
                                            new DSniper(600, EEnemyProjectileType.Light),
                                            new DSniper(650, EEnemyProjectileType.Light),
                                            new DSniper(700, EEnemyProjectileType.Light),
                                            new DSniper(750, EEnemyProjectileType.Light),
                                            new DSniper(800, EEnemyProjectileType.Light),
                                            new DSniper(850, EEnemyProjectileType.Light),
                                            new DSniper(900, EEnemyProjectileType.Light),
                                            new DSniper(950, EEnemyProjectileType.Light),
                                            new DSniper(1000, EEnemyProjectileType.Light),
                                            new DSniper(1050, EEnemyProjectileType.Light),
                                            new DSniper(1100, EEnemyProjectileType.Light),
                                            new DSniper(1150, EEnemyProjectileType.Light),
                                            new DSniper(1200, EEnemyProjectileType.Light),
                                            new DSniper(1250, EEnemyProjectileType.Light),
                                            new DSniper(1300, EEnemyProjectileType.Light),
                                            new DSniper(1350, EEnemyProjectileType.Light)),

                new EnemySection(50, false, new DSniper(50, EEnemyProjectileType.Light),
                                            new DSniper(100, EEnemyProjectileType.Light),
                                            new DSniper(150, EEnemyProjectileType.Light),
                                            new DSniper(200, EEnemyProjectileType.Light),
                                            new DSniper(250, EEnemyProjectileType.Light),
                                            new DSniper(300, EEnemyProjectileType.Light),
                                            new DSniper(350, EEnemyProjectileType.Light),
                                            new DSniper(400, EEnemyProjectileType.Light),
                                            new DSniper(450, EEnemyProjectileType.Light),
                                            new DSniper(500, EEnemyProjectileType.Light),
                                            new DSniper(550, EEnemyProjectileType.Light),
                                            new DSniper(600, EEnemyProjectileType.Light),
                                            new DSniper(650, EEnemyProjectileType.Light),
                                            new DSniper(700, EEnemyProjectileType.Light),
                                            new DSniper(750, EEnemyProjectileType.Light),
                                            new DSniper(800, EEnemyProjectileType.Light),
                                            new DSniper(850, EEnemyProjectileType.Light),
                                            new DSniper(900, EEnemyProjectileType.Light),
                                            new DSniper(950, EEnemyProjectileType.Light),
                                            new DSniper(1000, EEnemyProjectileType.Light),
                                            new DSniper(1050, EEnemyProjectileType.Light),
                                            new DSniper(1100, EEnemyProjectileType.Light),
                                            new DSniper(1150, EEnemyProjectileType.Light),
                                            new DSniper(1200, EEnemyProjectileType.Light),
                                            new DSniper(1250, EEnemyProjectileType.Light),
                                            new DSniper(1300, EEnemyProjectileType.Light),
                                            new DSniper(1350, EEnemyProjectileType.Light)),

                new EnemySection(100, false, new DSniper(50, EEnemyProjectileType.Light),
                                            new DSniper(100, EEnemyProjectileType.Light),
                                            new DSniper(150, EEnemyProjectileType.Light),
                                            new DSniper(200, EEnemyProjectileType.Light),
                                            new DSniper(250, EEnemyProjectileType.Light),
                                            new DSniper(300, EEnemyProjectileType.Light),
                                            new DSniper(350, EEnemyProjectileType.Light),
                                            new DSniper(400, EEnemyProjectileType.Light),
                                            new DSniper(450, EEnemyProjectileType.Light),
                                            new DSniper(500, EEnemyProjectileType.Light),
                                            new DSniper(550, EEnemyProjectileType.Light),
                                            new DSniper(600, EEnemyProjectileType.Light),
                                            new DSniper(650, EEnemyProjectileType.Light),
                                            new DSniper(700, EEnemyProjectileType.Light),
                                            new DSniper(750, EEnemyProjectileType.Light),
                                            new DSniper(800, EEnemyProjectileType.Light),
                                            new DSniper(850, EEnemyProjectileType.Light),
                                            new DSniper(900, EEnemyProjectileType.Light),
                                            new DSniper(950, EEnemyProjectileType.Light),
                                            new DSniper(1000, EEnemyProjectileType.Light),
                                            new DSniper(1050, EEnemyProjectileType.Light),
                                            new DSniper(1100, EEnemyProjectileType.Light),
                                            new DSniper(1150, EEnemyProjectileType.Light),
                                            new DSniper(1200, EEnemyProjectileType.Light),
                                            new DSniper(1250, EEnemyProjectileType.Light),
                                            new DSniper(1300, EEnemyProjectileType.Light),
                                            new DSniper(1350, EEnemyProjectileType.Light)),

                new EnemySection(10, true, new DSniper(50, EEnemyProjectileType.Normal),
                                            new DSniper(100, EEnemyProjectileType.Normal),
                                            new DSniper(150, EEnemyProjectileType.Normal),
                                            new DSniper(200, EEnemyProjectileType.Normal),
                                            new DSniper(250, EEnemyProjectileType.Normal),
                                            new DSniper(300, EEnemyProjectileType.Normal),
                                            new DSniper(350, EEnemyProjectileType.Normal),
                                            new DSniper(400, EEnemyProjectileType.Normal),
                                            new DSniper(450, EEnemyProjectileType.Normal),
                                            new DSniper(500, EEnemyProjectileType.Normal),
                                            new DSniper(550, EEnemyProjectileType.Normal),
                                            new DSniper(600, EEnemyProjectileType.Normal),
                                            new DSniper(650, EEnemyProjectileType.Normal),
                                            new DSniper(700, EEnemyProjectileType.Normal),
                                            new DSniper(750, EEnemyProjectileType.Normal),
                                            new DSniper(800, EEnemyProjectileType.Normal),
                                            new DSniper(850, EEnemyProjectileType.Normal),
                                            new DSniper(900, EEnemyProjectileType.Normal),
                                            new DSniper(950, EEnemyProjectileType.Normal),
                                            new DSniper(1000, EEnemyProjectileType.Normal),
                                            new DSniper(1050, EEnemyProjectileType.Normal),
                                            new DSniper(1100, EEnemyProjectileType.Normal),
                                            new DSniper(1150, EEnemyProjectileType.Normal),
                                            new DSniper(1200, EEnemyProjectileType.Normal),
                                            new DSniper(1250, EEnemyProjectileType.Normal),
                                            new DSniper(1300, EEnemyProjectileType.Normal),
                                            new DSniper(1350, EEnemyProjectileType.Normal)),


                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
                new EnemySection(70, false, new DSurpriser()),
            };

        }
    }
}